#! /bin/sh

# ls sliases
alias ls='ls --color=auto'
alias ll='ls -lAFh'
alias la='ls -A'
alias l='ls -cF'

# grep aliases
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

# sudo alias
alias ss='sudo -sE'

# parent directory aliases
alias ..='cd ..'
alias ...='cd ../..'

# Allows ssh to add the ssh key to the ssh-agent before trying to connect host
alias ssh='ssh-add -l 2> /dev/null || ssh-add ; ssh'

# Package manager aliases
# TODO: add more package managers like pacman
if [ -f $(which apt-get 2> /dev/null) ]
then
  alias agi='sudo apt-get install'
  alias ags='sudo apt-cache search'
  alias agu='sudo apt-get update'
  alias maj='sudo apt-get update && sudo apt-get upgrade'
elif [ -f $(which yum 2> /dev/null) ]
then
  alias agi='sudo yum install'
  alias ags='sudo yum search'
  alias maj='sudo yum update'
fi
