#! /bin/bash

# redo the previous command with sudo before it
# If args passed, behaves exactly like sudo
function rs {
  if [ $# = 0 ]
  then
    sudo $(history -p '!!')
  else
    sudo "$@"
  fi
}

# Create a directory and cd into
function mkcd {
  if [ $# = 1 ]
  then
    dir="$1"
    mkdir -p "$dir"
    cd "$dir"
  else
    echo "mkcd need 1 arg (and only 1)" >&2
    exit 1
  fi
}

# If ping is called without arg,
# just ping google server
function ping {
  if [ $# = 0 ]
  then
    command ping 8.8.8.8
  else
    command ping "$@"
  fi
}

