#! /bin/sh

# redo the previous command with sudo before it
# If args passed, behaves exactly like sudo
rs () {
  if [ $# = 0 ]
  then
    # not POSIX compliant
    sudo $(history -p '!!')
  else
    sudo "$@"
  fi
}

# Create a directory and cd into
mkcd () {
  if [ $# = 1 ]
  then
    dir="$1"
    mkdir -p "$dir"
    cd "$dir"
  else
    echo "mkcd need one arg (and only one)" >&2
    return 1
  fi
}

# If ping is called without arg,
# just ping google server
ping () {
  if [ $# = 0 ]
  then
    command ping 8.8.8.8
  else
    command ping "$@"
  fi
}

