#! /bin/bash
################################################################################
# Machine dependant custom completions
################################################################################

# variable used to store the LOCALRC path
export LOCALRC="$(pwd)"

# Add SCRIPT_PATH to current PATH if not already present
SCRIPT_PATH="$LOCALRC/scripts"
if [ -d "$SCRIPT_PATH" ] && ! ( echo "$PATH" | grep "$SCRIPT_PATH" &> /dev/null)
then
  PATH="$(pwd)/scripts:$PATH"
fi
unset SCRIPT_PATH

